- hosts: all 
  tasks: 
  -  name: does the testfile exist 
     stat: 
       path: /tmp/testfile 
     register: sym 
  -  debug:
       msg: "Our /tmp/testfile does not exist" 
     when: sym.stat.exists == False 
  -  debug:
       msg: "Our /tmp/testfile does exist"
     when: sym.stat.exists == True 

